# Generated by Django 4.2.3 on 2023-07-26 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('month', models.IntegerField()),
                ('day', models.IntegerField()),
                ('year', models.CharField(max_length=50)),
                ('avg_temp', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
