# Generated by Django 4.2.3 on 2023-07-27 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0002_temperature_delete_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temperature',
            name='avg_temp',
        ),
        migrations.AddField(
            model_name='temperature',
            name='avg_temp_C',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='temperature',
            name='avg_temp_F',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='region',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='year',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
