# Generated by Django 4.2.3 on 2023-07-27 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0003_remove_temperature_avg_temp_temperature_avg_temp_c_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temperature',
            name='avg_temp_C',
        ),
    ]
