# Generated by Django 4.2.3 on 2023-07-27 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0006_temperature_temperature_raw_month_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Temperature',
        ),
    ]
