# Generated by Django 4.2.3 on 2023-07-31 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0009_temperature_delete_temperature_avg_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temperature',
            name='day',
        ),
    ]
